name: Market CD

on:
    pull_request:
        branches:
            - 'main'
        types:
            - 'closed'

jobs:
    cd:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    token: ${{secrets.ONLINEMARKET_TOKEN}}

            -   name: Log in to Docker Hub
                    uses: docker/login-action@v2
                    with:
                        username: ${{ secrets.DOCKERHUB_USERNAME }}
                        password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Build & Push Docker Image
                uses: docker/build-push-action@v4
                    with:
                        context: .
                        file: ./Dockerfile
                        push: true
                        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}

            -   name: Deploy
                uses: appleboy/ssh-action@master
                id: deploy-prod
                with:
                    host: ${{ secrets.NCP_SERVER_IP }}
                    username: ${{ secrets.NCP_SERVER_USER }}
                    password: ${{ secrets.NCP_SERVER_PASSWORD }}
                    port: ${{ secrets.NCP_SERVER_SSH_PORT }}
                    script: |
                        sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
                        sudo docker rm -f $(docker ps -q -a)
                        sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}
                        docker-compose up -d
                        docker image prune -f
